### ISSUE TITLE
Update to bullseye

### ISSUE THREAD

**Issue by adamboardman** [gemian/gemian#14]
Debian are releasing bullseye soon so we should look to start the long process of re-porting/re-basing/re-building everything on the new base.

**Comment by adamboardman** [comment]
Nikita suggests looking at 'Droidian' when we get to this.

**Comment by mibry** [comment]
Was able to boot into Droidian using the UPports boot image and modifying it with yabit.py from https://github.com/g7/yabit. Working on getting wifi, bluetooth and mobile data to work.

**Comment by martinbutt** [comment]
Was any progress made on either Bullseye or Droidian? I can put some time towards this if there is a task list somewhere.

**Comment by mibry** [comment]
I was able to get droidian booting to Bulleye on my cosmo. Here is the repo I created with my initial work. https://github.com/mibry/cosmo-droidian. My cosmo is broken at the moment so I stopped work.

**Comment by martinbutt** [comment]
After going down a rabbit hole with Droidian and my Gemini PDA, neither of these will run, as the Gemini will only run Android 8, and not 9, which is the minimum. If someone else with a working Cosmo sees this, it would worth finishing @mibry's work as it looks like Gemian is abandoned now.

**Comment by mibry** [comment]
@martinbutt did you ask to the droidian telegram channel? I asked once if the gemini could be ported. I was told that it needed to be treble. I havn't had time to follow up but since gemini has a ubports and sailfish both with use halium it might be possible to  port droidian.

**Comment by martinbutt** [comment]
I did not contact them. Droidian sideloads onto an existing Android system, which must be Android 9+. This is a limitation of Drodian. The Gemini highest Android version is 8.1. Halium will run on Android 7.1+ and it is possible to get UBPorts running on a Gemini PDA, but to get Droidian running on Android 8 is no small task.

**Comment by shymega** [comment]
Yeah, this is an issue with the Gemini PDA. Maybe we should see if we can get Bullseye on the Cosmo & Astro, and then try and get Planet to update the Gemini to *at least* Android 9. This is in the benefit of Gemian and Linux on Planet devices, after all, which was part of the market...

**Comment by mibry** [comment]
Droidian booting and working on cosmo.

**Comment by adamboardman** [comment]
Closing as skipping bullseye jumping directly to bookworm, currently working on Astro.

**Comment by zero77** [comment]
@adamboardman 
Is there any documentation showing what repositories should be used.

**Comment by adamboardman** [comment]
I don't recommend trying this with anything other than an Astro (I've not started testing on the other devices), but its not like I can keep anything secret: https://github.com/gemian/gemian-debos-recipes/blob/bookworm/scripts/add-gemian-repos.sh gives:
```
deb [trusted=yes] http://gemian.thinkglobally.org/bookworm/ bookworm main
```

**Comment by sampavlovic** [comment]
Good to see you're still updating this, could we see phosh replacing KDE as the DE when you get it stable for the Cosmo? It feels perfect on this form factor

**Comment by shymega** [comment]
On Wed, Sep 27, 2023 at 03:21:24PM -0700, Sam Pavlovic wrote:
> Good to see you're still updating this, could we see phosh replacing KDE as the DE when you get it stable for the Cosmo? It feels perfect on this form factor
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/gemian/gemian/issues/14#issuecomment-1738177260
> You are receiving this because you commented.
>
> Message ID: ***@***.***>

I don't think Gemian should move away from KDE. But it's not my decision, it's up to Adam.

However, the postmarketOS efforts might be more what you want - you can choose the DE when you build the image. It's not ready yet, but there is progress on a mainline port of the Linux kernel...

Best wishes,
--
Dom Rodriguez
GPG Fingerprint: EB0D 45E6 D0DC 1BA1 A2B5  FC24 72DC F123 1E54 BD43

**Comment by zero77** [comment]
Is this accurate or is there more that's now working or not, like the touch screen.
https://wiki.postmarketos.org/wiki/Planet_Computers_Cosmo_Communicator_(planet-cosmocom)

**Comment by shymega** [comment]
@zero77 I updated that recently. Currently, the issues are:

- We can't use `libhybris` or Halium, unlike Gemian/UBPort.s
- The kernel needs work to be mainlined.
- I need to extract the keyboard driver, and STM32 drivers as out-of-tree modules, so the above can be achieved.

Not entirely exhaustive. It may be best to come and discuss in the specialised Telegram group for pmOS on Planet devices.
