### ISSUE TITLE
Cosmo screen closed doesn't wake up upon screen opening

### ISSUE THREAD

**Issue by mibry** [gemian/gemian#15]
Cosmo does not recover from screen closed. 

Codi displays the correct time, when I plug the cosmo into usb2 cable and connect it to a linux computer I get no connection to be able to ssh into the cosmo.

**Comment by adamboardman** [comment]
I'm assuming this is after you've installed the preview build, unfortunately this is not enough information for me to have any idea of how to help you. There was a bug with the move to lxc-android where the screen refused to return but that was fixed with a re-ordering of the brightness settings: https://github.com/gemian/xf86-video-hwcomposer/commit/f6cf58b50d4177670f718e573b32667960db2c54 and you could still USB-Tether in.

I've added a new page to the wiki on reporting bugs: [ReportingBugs](https://github.com/gemian/gemian/wiki/ReportingBugs) which may give some pointers. I assume you mean the USB Tethering as the usual way back in when screen and wifi have failed - [Debugging#usb-tethering](https://github.com/gemian/gemian/wiki/Debugging#usb-tethering)

If that's the case then your probably going to have to reboot with holding the Esc(on) key for a long time.

**Comment by mibry** [comment]
Here is the log export from syslog which has the last entry before I rebooted my cosmo:

Apr 28 14:21:34 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:34 cosmocom systemd-udevd[8350]: Process '/usr/sbin/tlp auto' failed with exit code 4.
Apr 28 14:21:34 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:34 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:34 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:34 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:34 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:34 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:34 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:34 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:34 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:34 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:34 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:34 cosmocom kernel: [ 8929.678078]  (0)[26202:kworker/0:3][msdc]msdc1 -> !!! Set<400KHz> Source<191999KHz> -> sclk<399KHz> timing<0> mode<0> div<120> hs400_div_dis<0>
Apr 28 14:21:34 cosmocom kernel: [ 8929.686449]  (0)[26202:kworker/0:3][msdc]msdc1 -> !!! Set<200000KHz> Source<191999KHz> -> sclk<191999KHz> timing<6> mode<1> div<0> hs400_div_dis<0>
Apr 28 14:21:34 cosmocom kernel: [ 8929.688572]  (0)[26202:kworker/0:3][msdc]msdc1 -> Card insert<1> Block bad card<0>, mrq<          (null)> claimed<1> pwrcnt<0> <- msdc_ops_get_cd() : L<4523> PID<kworker/0:3><0x665a>
Apr 28 14:21:35 cosmocom kernel: [ 8929.841417]  (2)[5758:kworker/u16:4]PM: suspend entry 2021-04-28 04:21:35.067036188 UTC
Apr 28 14:21:35 cosmocom kernel: [ 8929.841463]  (2)[5758:kworker/u16:4]PM: Syncing filesystems ... done.
Apr 28 14:21:35 cosmocom kernel: [ 8929.957774]  (0)[5758:kworker/u16:4][msdc]msdc1 power off
Apr 28 14:21:35 cosmocom kernel: [ 8929.968831]  (0)[5758:kworker/u16:4]PM: Wakeup pending, aborting suspend
Apr 28 14:21:35 cosmocom kernel: [ 8929.968892]  (0)[5758:kworker/u16:4]last active wakeup source: bat_percent_notify_lock wakelock
Apr 28 14:21:35 cosmocom kernel: [ 8929.968921]  (0)[5758:kworker/u16:4]PM: Some devices failed to suspend, or early wake event detected
Apr 28 14:21:35 cosmocom kernel: [ 8929.968973]  (0)[5758:kworker/u16:4]PM: resume of devices complete after 0.032 msecs
Apr 28 14:21:35 cosmocom kernel: [ 8929.986533]  (1)[5758:kworker/u16:4]PM: suspend exit 2021-04-28 04:21:35.212152868 UTC
Apr 28 14:21:35 cosmocom kernel: [ 8929.986581]  (1)[5758:kworker/u16:4]PM: suspend entry 2021-04-28 04:21:35.212203022 UTC
Apr 28 14:21:35 cosmocom kernel: [ 8929.986603]  (0)[26202:kworker/0:3]PM: Syncing filesystems ...
Apr 28 14:21:35 cosmocom kernel: [ 8929.989931]  (0)[26202:kworker/0:3][msdc]msdc1 power on
Apr 28 14:21:35 cosmocom kernel: [ 8930.017506]  (0)[26202:kworker/0:3][msdc]msdc1 -> !!! Set<260KHz> Source<191999KHz> -> sclk<259KHz> timing<0> mode<0> div<185> hs400_div_dis<0>
Apr 28 14:21:35 cosmocom kernel: [ 8930.018731]  (0)[26202:kworker/0:3][msdc]msdc1 -> !!! Set<400KHz> Source<191999KHz> -> sclk<399KHz> timing<0> mode<0> div<120> hs400_div_dis<0>
Apr 28 14:21:35 cosmocom kernel: [ 8930.089394]  (6)[5758:kworker/u16:4]done.
Apr 28 14:21:35 cosmocom NetworkManager[1085]: <info>  [1619583695.3335] manager: sleep: sleep requested (sleeping: no  enabled: yes)
Apr 28 14:21:35 cosmocom NetworkManager[1085]: <info>  [1619583695.3338] device (wlan0): state change: unavailable -> unmanaged (reason 'sleeping', sys-iface-state: 'managed')
Apr 28 14:21:35 cosmocom NetworkManager[1085]: <info>  [1619583695.3345] device (wlan0): set-hw-addr: reset MAC address to 00:03:AA:BC:8B:EC (unmanage)
Apr 28 14:21:35 cosmocom NetworkManager[1085]: <info>  [1619583695.3375] device (ril_1): state change: disconnected -> unmanaged (reason 'sleeping', sys-iface-state: 'managed')
Apr 28 14:21:35 cosmocom NetworkManager[1085]: <info>  [1619583695.3379] device (ril_0): state change: disconnected -> unmanaged (reason 'sleeping', sys-iface-state: 'managed')
Apr 28 14:21:35 cosmocom NetworkManager[1085]: <info>  [1619583695.3383] manager: NetworkManager state is now ASLEEP
Apr 28 14:21:35 cosmocom systemd[1]: Starting TLP suspend/resume...
Apr 28 14:21:35 cosmocom media-hub-server[2724]:   Output to wired headphone: false
Apr 28 14:21:35 cosmocom media-hub-server[2724]:   Output to wired headset: false
Apr 28 14:21:35 cosmocom media-hub-server[2724]: [TT 2021-04-28 02:36:56.238942] [service_skeleton.cpp:657@is_multimedia_role]
Apr 28 14:21:35 cosmocom media-hub-server[2724]: [TT 2021-04-28 02:38:38.711834] [service_skeleton.cpp:657@is_multimedia_role]
Apr 28 14:21:35 cosmocom media-hub-server[2724]: [TT 2021-04-28 02:41:02.010774] [service_skeleton.cpp:657@is_multimedia_role]
Apr 28 14:21:35 cosmocom media-hub-server[2724]: [TT 2021-04-28 02:42:24.859564] [service_skeleton.cpp:657@is_multimedia_role]
Apr 28 14:21:35 cosmocom media-hub-server[2724]: [TT 2021-04-28 02:44:07.759806] [service_skeleton.cpp:657@is_multimedia_role]
Apr 28 14:21:35 cosmocom media-hub-server[2724]: [TT 2021-04-28 02:46:26.873028] [service_skeleton.cpp:657@is_multimedia_role]
Apr 28 14:21:35 cosmocom systemd[1]: Started TLP suspend/resume.
Apr 28 14:21:35 cosmocom systemd[1]: Reached target Sleep.
Apr 28 14:21:35 cosmocom systemd[1]: Starting Suspend...
Apr 28 14:21:35 cosmocom systemd-sleep[20988]: Suspending system...
Apr 28 14:21:35 cosmocom kernel: [ 8930.277595]  (0)[26202:kworker/0:3][msdc]msdc1 -> !!! Set<400KHz> Source<191999KHz> -> sclk<399KHz> timing<0> mode<0> div<120> hs400_div_dis<0>
Apr 28 14:21:35 cosmocom kernel: [ 8930.285984]  (0)[26202:kworker/0:3][msdc]msdc1 -> !!! Set<200000KHz> Source<191999KHz> -> sclk<191999KHz> timing<6> mode<1> div<0> hs400_div_dis<0>
Apr 28 14:21:35 cosmocom kernel: [ 8930.288108]  (0)[26202:kworker/0:3][msdc]msdc1 -> Card insert<1> Block bad card<0>, mrq<          (null)> claimed<1> pwrcnt<0> <- msdc_ops_get_cd() : L<4523> PID<kworker/0:3><0x665a>
Apr 28 14:21:35 cosmocom kernel: [ 8930.290825]  (4)[5758:kworker/u16:4]PM: Wakeup pending, aborting suspend
Apr 28 14:21:35 cosmocom kernel: [ 8930.290850]  (4)[5758:kworker/u16:4]active wakeup source: WLAN timeout
Apr 28 14:21:35 cosmocom systemd-sleep[20988]: Failed to suspend system. System resumed again: Interrupted system call
Apr 28 14:21:35 cosmocom kernel: [ 8930.302419]  (0)[26202:kworker/0:3][msdc]msdc1 -> Card insert<1> Block bad card<0>, mrq<          (null)> claimed<1> pwrcnt<0> <- msdc_ops_get_cd() : L<4523> PID<kworker/0:3><0x665a>
Apr 28 14:21:35 cosmocom kernel: [ 8930.302540]  (0)[5758:kworker/u16:4]PM: suspend exit 2021-04-28 04:21:35.528162863 UTC
Apr 28 14:21:35 cosmocom systemd[1]: systemd-suspend.service: Main process exited, code=exited, status=1/FAILURE
Apr 28 14:21:35 cosmocom systemd[1]: systemd-suspend.service: Failed with result 'exit-code'.
Apr 28 14:21:35 cosmocom systemd[1]: Failed to start Suspend.
Apr 28 14:21:35 cosmocom systemd[1]: Dependency failed for Suspend.
Apr 28 14:21:35 cosmocom systemd[1]: suspend.target: Job suspend.target/start failed with result 'dependency'.
Apr 28 14:21:35 cosmocom systemd[1]: Stopped target Sleep.
Apr 28 14:21:35 cosmocom systemd[1]: Stopping TLP suspend/resume...
Apr 28 14:21:35 cosmocom NetworkManager[1085]: <info>  [1619583695.5787] manager: sleep: wake requested (sleeping: yes  enabled: yes)
Apr 28 14:21:35 cosmocom NetworkManager[1085]: <info>  [1619583695.5794] device (wlan0): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'managed')
Apr 28 14:21:35 cosmocom NetworkManager[1085]: <info>  [1619583695.5822] device (ril_1): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'managed')
Apr 28 14:21:35 cosmocom kernel: [ 8930.354826]  (2)[1085:NetworkManager]IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
Apr 28 14:21:35 cosmocom NetworkManager[1085]: <info>  [1619583695.5833] device (ril_1): modem state 'enabling'
Apr 28 14:21:35 cosmocom NetworkManager[1085]: <info>  [1619583695.5837] device (ril_0): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'managed')
Apr 28 14:21:35 cosmocom NetworkManager[1085]: <info>  [1619583695.5844] manager: NetworkManager state is now DISCONNECTED
Apr 28 14:21:35 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:35 cosmocom NetworkManager[1085]: <info>  [1619583695.5897] device (ril_1): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'managed')
Apr 28 14:21:35 cosmocom NetworkManager[1085]: <info>  [1619583695.5903] device (ril_0): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'managed')
Apr 28 14:21:35 cosmocom kernel: [ 8930.361325]  (2)[5758:kworker/u16:4]PM: suspend entry 2021-04-28 04:21:35.586947263 UTC
Apr 28 14:21:35 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:35 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:35 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:35 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:35 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:35 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:35 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:35 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:35 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:35 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:35 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:35 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:35 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:35 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:35 cosmocom upowerd[2498]: energy_full (10.917876) is greater than energy_full_design (0.000000)
Apr 28 14:21:35 cosmocom systemd[1]: tlp-sleep.service: Succeeded.
Apr 28 14:21:35 cosmocom systemd[1]: Stopped TLP suspend/resume.
Apr 28 14:21:36 cosmocom kernel: [ 8930.361374] -(2)[24115:python3]PM: Syncing filesystems ...
Apr 28 14:21:36 cosmocom kernel: [ 8931.371519] -(2)[24115:python3]mtk-8250-dma: [DMA] Polling flush timeout
Apr 28 14:21:36 cosmocom kernel: [ 8931.371770]  (0)[5758:kworker/u16:4]done.
Apr 28 14:21:36 cosmocom kernel: [ 8931.375238]  (5)[5758:kworker/u16:4]PM: Wakeup pending, aborting suspend
Apr 28 14:21:36 cosmocom kernel: [ 8931.375291]  (5)[5758:kworker/u16:4]last active wakeup source: WLAN timeout
Apr 28 14:21:36 cosmocom kernel: [ 8931.387243]  (1)[9397:kworker/1:3][msdc]msdc1 -> Card insert<1> Block bad card<0>, mrq<          (null)> claimed<1> pwrcnt<0> <- msdc_ops_get_cd() : L<4523> PID<kworker/1:3><0x24b5>
Apr 28 14:21:36 cosmocom kernel: [ 8931.387333]  (0)[5758:kworker/u16:4]PM: suspend exit 2021-04-28 04:21:36.612963088 UTC
Apr 28 14:21:36 cosmocom kernel: [ 8931.387368]  (0)[5758:kworker/u16:4]PM: suspend entry 2021-04-28 04:21:36.612999165 UTC
Apr 28 18:26:39 cosmocom systemd[1]: Starting Flush Journal to Persistent Storage...
Apr 28 18:26:39 cosmocom kernel: [    0.000000] -(0)[0:swapper]Booting Linux on physical CPU 0x0
Apr 28 18:26:39 cosmocom kernel: [    0.000000] -(0)[0:swapper]Initializing cgroup subsys cpuset
Apr 28 18:26:39 cosmocom kernel: [    0.000000] -(0)[0:swapper]Initializing cgroup subsys cpu
Apr 28 18:26:39 cosmocom kernel: [    0.000000] -(0)[0:swapper]Initializing cgroup subsys cpuacct
Apr 28 18:26:39 cosmocom kernel: [    0.000000] -(0)[0:swapper]Linux version 4.4.146 (pbuilder@quasar) (gcc version 8.3.0 (Debian 8.3.0-6) ) #1 SMP PREEMPT Mon Apr 19 21:45:57 UTC 2021
Apr 28 18:26:39 cosmocom kernel: [    0.000000] -(0)[0:swapper]Boot CPU: AArch64 Processor [410fd034]
Apr 28 18:26:39 cosmocom kernel: [    0.000000] -(0)[0:swapper]mrdump_get_cb: mrdump_cbaddr=0x000000000011e000, mrdump_cbsize=0x0000000000002000
Apr 28 18:26:39 cosmocom kernel: [    0.000000] -(0)[0:swapper][PHY layout]mblock-13-ccci   :   0x8a000000 - 0x8b5fffff (0x1600000)
Apr 28 18:26:39 cosmocom kernel: [    0.000000] -(0)[0:swapper][PHY layout]mblock-11-ccci   :   0x8c000000 - 0x8c0fffff (0x100000)
Apr 28 18:26:39 cosmocom systemd[1]: Reached target Local File Systems (Pre).
Apr 28 18:26:39 cosmocom systemd[1]: Mounting Droid mount for /config...

My cosmo has the prerelease 4 of gemian, I have also installed tlp and cpufreq but not installed any other packages since flashing the cosmo. I ran a dist-upgrade this morning and will test the standby functionally with activating tlp or cpufreq
Hope the extra info helps.

**Comment by adamboardman** [comment]
If you could try without using tlp/cpufreq, you do get a 'tlp-sleep.service: Succeeded.' just before the date jump so that would be my most likely candidate for investigation. The plan is to fix issue #12 so you won't need to worry about these things in the future. I'm inclined to close this as a duplicate to be fixed by that fix.

**Comment by mibry** [comment]
I am happy for this to be closed.
