### ISSUE TITLE
Requests?

### ISSUE THREAD

**Issue by FOSSBOSS** [gemian/gemian#23]
I have a load of requests, and questions. oh yay, I bet you'll say. 
actually, I'm wondering if this project is even still active.
a vim ( not vi )package in the Repos would be helpful.

I installed it from source.

**Comment by shymega** [comment]
I'm not able to make sense of this issue, but please feel free to comment with further info.

**Comment by adamboardman** [comment]
```
apt search vim
```
Its a standard Debian package and so gives:
vim/oldoldstable... (on a Gemini)
vim/oldstable..... (on a Cosmo)
vim/testing... (on a Astro)

Project was on strike for 15 months.
