### ISSUE TITLE
ERROR the certificate of gemian.thinkglobally.org is not trusted / has expired

### ISSUE THREAD

**Issue by ech67** [gemian/gemian#29]
Hi,
Thanks for all your effort about this project!
I install Gemian following your explainations (TP3 + geminifrench (OESF Forum).
I'm not able to add repository archive key because wget returns the two errors mentioned above.
Thank you for your help!

Edit: surprisingly there's no problem on my computer, on the same wifi network.

**Comment by ech67** [comment]
ok. I solved it:  --no-Check-certificate.
Correct only because of the specific level of confidence.

**Comment by ech67** [comment]
-

**Comment by shymega** [comment]
This should be re-opened, as the cert does need renewing.

cc: @adamboardman
