### ISSUE TITLE
Gemian repository fingerprint does not match current key

### ISSUE THREAD

**Issue by lzmartinico** [gemian/gemian#3]
The gemian repository [webpage](https://gemian.thinkglobally.org/) recommends adding a new key to the apt keystore; however the fingerprint of the downloadable key does not match the one advertised on the same webpage. Some threads on the oesf forums suggest the key has been updated; if this is legitimate, it should be reflected on the webpage

**Comment by adamboardman** [comment]
Fingerprint updated, thanks for the nudge.
