### ISSUE TITLE
can't free disk space

### ISSUE THREAD

**Issue by basiliscos** [gemian/gemian#4]
```
root@localhost:~# df -h
Filesystem       Size  Used Avail Use% Mounted on
udev             1.9G     0  1.9G   0% /dev
tmpfs            378M   39M  339M  11% /run
/dev/mmcblk0p29   51G  3.9G   44G   9% /
tmpfs            1.9G     0  1.9G   0% /dev/shm
tmpfs            5.0M     0  5.0M   0% /run/lock
tmpfs            1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/loop0       564M  560M     0 100% /system
/dev/mmcblk0p28  419M  408K  410M   1% /cache
/dev/mmcblk0p8   3.9M   68K  3.7M   2% /protect_f
/dev/mmcblk0p9   8.3M   60K  8.0M   1% /protect_s
/dev/mmcblk0p5   3.9M   52K  3.7M   2% /nvcfg
/dev/mmcblk0p6    27M  7.8M   19M  30% /nvdata
tmpfs            378M  4.0K  378M   1% /run/user/100000
tmpfs            378M     0  378M   0% /run/user/109
root@localhost:~# sudo resize2fs -p /dev/mmcblk0p29 
resize2fs 1.43.4 (31-Jan-2017)
resize2fs: Device or resource busy while trying to open /dev/mmcblk0p29
```

what can I do? I ssh'ed into the device...

**Comment by adamboardman** [comment]
This should be being done every boot, either for main partition or stowaways:
https://github.com/gemian/initramfs-tools-halium/blob/native/scripts/geminipda#L99
Or for lvm mounted:
https://github.com/gemian/initramfs-tools-halium/blob/native/scripts/geminipda#L279
FYI: My device I picked the 90G for linux and it shows 83G in df -h I think you should take the suggested size with a pinch of salt. I'd be interested in the size of your android userdata partition I expect its bigger than 60G even though you presumably picked the 60/60 even split.

**Comment by basiliscos** [comment]
thank you!
